### ISSUE TITLE
README for building should mention libgirepository1.0-dev, libgtk-3-dev dependencies

### ISSUE THREAD

**Issue by unhammer** [lettier/gifcurry#17]
When building the `git clone` with `stack build`, I get
```
    Configuring haskell-gi-0.20.3...                                  
    Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2: The pkg-config package                                                                                                                              
    'gobject-introspection-1.0' version >=1.32 is required but it could not be
    found.     
```
which is solved with `sudo apt-get install libgirepository1.0-dev` on Ubuntu. 

followed by 
```
    Did not find a GI repository for Gdk-3.0 in                                                                                                                                                   
    ["/usr/share/xubuntu/gir-1.0","/usr/share/xfce4/gir-1.0","/usr/local/share/gir-1.0","/usr/share/gir-1.0","/usr/share/gir-1.0"].                                                                                                                                                            
    CallStack (from HasCallStack):                                                                                                                                                                
    error, called at lib/Data/GI/GIR/Repository.hs:89:20 in                                                                                                                                       
    haskell-gi-0.20.3-GkK5Bv8ALzbESiQXUDFHfm:Data.GI.GIR.Repository    
```
which is solved with `sudo apt-get install libgtk-3-dev` on Ubuntu. 

I'd send a PR against the README, but I didn't quite understand in what section of the build instruction list to put it ("github"? But then why are there both mac→compile and github compile instructions?)

**Comment by lettier** [comment]
Hello @unhammer 

I do apologize for the confusion. GObject Introspection is a dependency of a dependency of Gifcurry.

The GitHub build instructions are left intentionally vague since the platform is unknown in that context. The macOS build instructions do go through the step of installing all of the transitive dependencies via Homebrew.

Still, I have now referenced it in all of the appropriate places.

I noticed you are using Xubuntu. If you'd like, you can skip building Gifcurry and use the pre-built binaries found on the [releases](https://github.com/lettier/gifcurry/releases) page.

* [AppImage](https://github.com/lettier/gifcurry/tree/master#appimage-gui-only)
   * Requires no installation
   * Runs on most Linux distributions
   * Includes only the GUI
* [Compressed Binaries](https://github.com/lettier/gifcurry/tree/master#debianubuntumint)
   * Requires no installation
   * Should run on most Linux distributions
   * Includes both the CLI and GUI

:+1:

**Comment by unhammer** [comment]
Thanks! I did see the releases (love how easy you made it to run), but this time I was just playing around with the code, so wanted to be able to compile.
