### ISSUE TITLE
No video preview Ubuntu 18.04

### ISSUE THREAD

**Issue by mt7479** [lettier/gifcurry#23]
Gifcurry displays the following warning when browsing for a input file:

`gtksink not found. No video preview available. Install the gstreamer 1.0 bad plugins version 1.8 or higher.`

```
apt-cache policy gstreamer1.0-plugins-bad
gstreamer1.0-plugins-bad:
  Installed: 1.14.0-1ubuntu1
  Candidate: 1.14.0-1ubuntu1
  Version table:
 *** 1.14.0-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        100 /var/lib/dpkg/status
```

I'm using the Appimage build.

**Comment by lettier** [comment]
Hello @mt7479,

Thank you for opening up an issue.

The `gtksink` plugin went from the "bad" to "good" plugins in GStreamer 1.14.

Apparently Ubuntu packages up `gtksink` in its own separate package instead of leaving it in the `gstreamer1.0-plugins-good` package.

Please run the following.

```bash
sudo apt-get install gstreamer1.0-gtk3
```

Afterwards, Gifcurry will have `gtksink`.

I will update the documentation in the next release.

:+1:

**Comment by mt7479** [comment]
Preview works now. Thanks for the fast reply!

Lettier <notifications@github.com> schrieb am So., 13. Mai 2018, 21:46:

**Comment by mt7479** [comment]
Thanks for the fast reply. Preview is working as expected.

**Comment by felixcatto** [comment]
Can't install this plugin :( Ubuntu 16.04 just does't have it

**Comment by IoriBranford** [comment]
On Arch-based distros, you have to install [gst-plugin-gtk](https://archlinux.org/packages/extra/x86_64/gst-plugin-gtk/) which is considered an optional component. So it's not automatically installed with whatever metapackage it's part of.
