### ISSUE TITLE
Feature requests for "Width & Quality" section: output width + framerate

### ISSUE THREAD

**Issue by strawhatgami** [lettier/gifcurry#28]
Hello,

I think the "Width & Quality" section on the GUI can be improved in 2 points:
- The width in input should be the width of the output gif. Now the width of the ouput gif is the input width multiplied by the crop ratio.
- Allow to set the framerate exactly (e.g. 7.5 FPS), instead of put it in the "Quality" dropdown list as it is now

Would make the app even better imho.

Cheers!

Note: I use gifcurry-4.0.0.0-x86_64.AppImage on Ubuntu 18.04

**Comment by lettier** [comment]
Hello @strawhatgami,

Thank you for the feature request.

I will add these changes in Gifcurry's next release.

- The specified width will be the final width of the output after any cropping.
- Remove the quality setting.
- Add a frame rate setting.
- Add a number of colours setting. 

Note that the number of colours used will have to be exposed as well since the quality setting handles both the frame rate and number of colours used. 

Oh and thank you for starring Gifcurry.

:+1:

**Comment by lettier** [comment]
Hello @strawhatgami,

You can now control the frame rate (FPS) and colour count directly. The width setting is the final output width after cropping.
Try it out in version [5.0.0.0](https://github.com/lettier/gifcurry/releases/tag/5.0.0.0).

:+1:
